baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Emerald Semaphore of Keta-9'
theme = 'mainroad'
pagination.pagerSize = "10"
renderer.unsafe = true
enableRobotsTXT = true

[Params.style.vars]
  highlightColor = "#2de278ff"

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["recent", "categories", "taglist", "sidemenu"]

[Params]
  post_meta = ["author", "date", "categories"]
  description = "Wiki for the movie The Emerald Semaphore of Keta-9"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true